---
- hosts: tomcat-servers
  tasks:
    - name: Stop Tomcat
      command: sh /usr/share/tomcat/bin/shutdown.sh
      become: true
      become_user: tomcat

    - name: Remove Tomcat
      file:
        path: /opt/apache-tomcat-7.0.61
        state: absent

    - name: remove user "tomcat"
      user:
        name: tomcat
        state: absent

    - name: remove group "tomcat"
      group:
        name: tomcat
        state: absent
